import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('api', {
    ping: () => ipcRenderer.invoke('ping'),
    getProducts: (params: any) => ipcRenderer.invoke('get-products', params),
    addProduct: (product: any) => ipcRenderer.invoke('add-product', product),
    updateProduct: (product: any) => ipcRenderer.invoke('update-product', product),
    deleteProduct: (id: number) => ipcRenderer.invoke('delete-product', id),
    deleteAllProducts: () => ipcRenderer.invoke('delete-all-products'),
    adjustStock: (data: any) => ipcRenderer.invoke('adjust-stock', data),
    getStockMovements: (productId: number) => ipcRenderer.invoke('get-stock-movements', productId),
    processSale: (saleData: any) => ipcRenderer.invoke('process-sale', saleData),
    getSaleDetails: (saleId: number) => ipcRenderer.invoke('get-sale-details', saleId),
    searchSalesByPhone: (phone: string) => ipcRenderer.invoke('search-sales-by-phone', phone),
    searchSalesByCustomerName: (name: string) => ipcRenderer.invoke('search-sales-by-customer-name', name),
    getRecentCustomers: (params: any) => ipcRenderer.invoke('get-recent-customers', params),
    getCustomers: (params: any) => ipcRenderer.invoke('get-customers', params),
    addCustomer: (customer: any) => ipcRenderer.invoke('add-customer', customer),
    updateCustomer: (customer: any) => ipcRenderer.invoke('update-customer', customer),
    checkCustomerExists: (phone: string) => ipcRenderer.invoke('check-customer-exists', phone),
    getCustomerDetails: (id: number) => ipcRenderer.invoke('get-customer-details', id),
    addInstallment: (data: any) => ipcRenderer.invoke('add-installment', data),
    getSaleForRefund: (saleId: number) => ipcRenderer.invoke('get-sale-for-refund', saleId),
    processRefund: (data: any) => ipcRenderer.invoke('process-refund', data),
    getRefunds: (params: any) => ipcRenderer.invoke('get-refunds', params),
    holdSale: (data: any) => ipcRenderer.invoke('hold-sale', data),
    getHeldSales: () => ipcRenderer.invoke('get-held-sales'),
    deleteHeldSale: (id: number) => ipcRenderer.invoke('delete-held-sale', id),
    getSalesReport: (params: { startDate: string; endDate: string; page?: number; limit?: number }) => ipcRenderer.invoke('get-sales-report', params),

    // Analytics
    getExecutiveOverview: (range: any) => ipcRenderer.invoke('get-executive-overview', range),
    getCustomerIntelligence: (range: any) => ipcRenderer.invoke('get-customer-intelligence', range),
    getProductIntelligence: (range: any) => ipcRenderer.invoke('get-product-intelligence', range),
    getOperationalIntelligence: (range: any) => ipcRenderer.invoke('get-operational-intelligence', range),
    debugDates: () => ipcRenderer.invoke('debug-dates'),

    getHPSummary: () => ipcRenderer.invoke('get-hp-summary'),
    getHirePurchaseAgreements: (filter: any) => ipcRenderer.invoke('get-hire-purchase-agreements', filter),
    getOverdueAgreements: () => ipcRenderer.invoke('get-overdue-agreements'),
    getDailySummary: (date: string) => ipcRenderer.invoke('get-daily-summary', date),
    closeDayTransactions: (data: any) => ipcRenderer.invoke('close-day-transactions', data),
    getClosingHistory: () => ipcRenderer.invoke('get-closing-history'),
    backupDatabase: () => ipcRenderer.invoke('backup-database'),
    restoreDatabase: () => ipcRenderer.invoke('restore-database'),
    getAuditLogs: (params?: any) => ipcRenderer.invoke('get-audit-logs', params),
    login: (credentials: any) => ipcRenderer.invoke('login', credentials),
    getUsers: () => ipcRenderer.invoke('get-users'),
    createUser: (user: any) => ipcRenderer.invoke('create-user', user),
    deleteUser: (id: number) => ipcRenderer.invoke('delete-user', id),
    resetUserPassword: (data: any) => ipcRenderer.invoke('reset-user-password', data),
    updateUser: (user: any) => ipcRenderer.invoke('update-user', user),
    getTopProducts: (limit?: number) => ipcRenderer.invoke('get-top-products', { limit }),
    getDashboardStats: () => ipcRenderer.invoke('get-dashboard-stats'),
    getDailySalesChart: (days?: number) => ipcRenderer.invoke('get-daily-sales-chart', days),
    getInventorySummary: () => ipcRenderer.invoke('get-inventory-summary'),
    getCategories: () => ipcRenderer.invoke('get-categories'),
    addCategory: (category: any) => ipcRenderer.invoke('add-category', category),
    updateCategory: (category: any) => ipcRenderer.invoke('update-category', category),
    deleteCategory: (id: number) => ipcRenderer.invoke('delete-category', id),
    getCategoryPerformance: (params: { startDate: string; endDate: string }) => ipcRenderer.invoke('get-category-performance', params),
    printReceipt: () => ipcRenderer.invoke('print-receipt'),
    getSettings: () => ipcRenderer.invoke('get-settings'),
    updateSettings: (settings: any) => ipcRenderer.invoke('update-settings', settings),

    // Image & Discount Features
    selectProductImage: () => ipcRenderer.invoke('select-product-image'),
    getProductImagePath: (fileName: string) => ipcRenderer.invoke('get-product-image-path', fileName),
    getDiscounts: () => ipcRenderer.invoke('get-discounts'),
    addDiscount: (discount: any) => ipcRenderer.invoke('add-discount', discount),
    updateDiscount: (discount: any) => ipcRenderer.invoke('update-discount', discount),
    deleteDiscount: (id: number) => ipcRenderer.invoke('delete-discount', id),

    // Bulk Import
    downloadTemplate: () => ipcRenderer.invoke('download-template'),
    selectExcelFile: () => ipcRenderer.invoke('select-excel-file'),
    importProducts: (filePath: string, tripName?: string) => ipcRenderer.invoke('import-products', filePath, tripName),
    getTripNames: () => ipcRenderer.invoke('get-trip-names'),

    // Setup Handlers
    checkHasUsers: () => ipcRenderer.invoke('setup:has-users'),
    initializeSetup: (payload: any) => ipcRenderer.invoke('setup:initialize', payload),
    getAppInfo: () => ipcRenderer.invoke('get-app-info'),
    openDataFolder: () => ipcRenderer.invoke('open-data-folder'),
    openExportsFolder: () => ipcRenderer.invoke('open-exports-folder'),

    // License Handlers
    getLicenseStatus: () => ipcRenderer.invoke('license:get-status'),
    activateLicense: (payload: any) => ipcRenderer.invoke('license:activate', payload),
    deactivateLicense: () => ipcRenderer.invoke('license:deactivate'),

    // Update Handlers
    checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
    downloadUpdate: () => ipcRenderer.invoke('download-update'),
    installUpdate: () => ipcRenderer.invoke('install-update'),
    listBackups: () => ipcRenderer.invoke('list-backups'),
    restoreBackup: (backupPath: string) => ipcRenderer.invoke('restore-backup', backupPath),
    deleteBackup: (backupPath: string) => ipcRenderer.invoke('delete-backup', backupPath),

    // Update Event Listeners
    onUpdateAvailable: (callback: any) => ipcRenderer.on('update-available', (_event, data) => callback(data)),
    onUpdateNotAvailable: (callback: any) => ipcRenderer.on('update-not-available', () => callback()),
    onUpdateDownloadProgress: (callback: any) => ipcRenderer.on('update-download-progress', (_event, progress) => callback(progress)),
    onUpdateDownloaded: (callback: any) => ipcRenderer.on('update-downloaded', (_event, data) => callback(data)),
    onUpdateError: (callback: any) => ipcRenderer.on('update-error', (_event, error) => callback(error)),
});